#!/bin/bash
# logviever
# Для прекращения работы сценария нужно нажать комбинацию клавиш <Ctrl>+<C>
# Интервал обновления в секундах
INT=3
while [ true ]
do
 # Выводим последние 15 строк журнала
 tail -n 15 $1
 # Ждем
 sleep $INT
 # Две пустые строки
 echo; echo
done

#Формат вызова следующий:
#./сценарий файл_журнала
#Например:
#./script /var/log/messages
#./script /var/log/syslog
#bash logviever /var/log/syslog
